project_type: node
slug: princefoods
port: 3000

domains:
  prod: prince-v.com
  admin: admin.prince-v.com

deploy_targets:
  main-hetz: hetzner
  dev: vercel
  preview: vercel

pgadmin_subdomain: dbui
pgadmin_subdomain: db
