-- CreateTable
CREATE TABLE "Product" (
    "id" TEXT NOT NULL,
    "fieldType" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "productImageUrl" TEXT,
    "collection" TEXT,
    "sku" TEXT,
    "ribbon" TEXT,
    "price" DOUBLE PRECISION,
    "surcharge" DOUBLE PRECISION,
    "visible" BOOLEAN NOT NULL DEFAULT true,
    "discountMode" TEXT,
    "discountValue" DOUBLE PRECISION,
    "inventory" TEXT,
    "weight" DOUBLE PRECISION,
    "cost" DOUBLE PRECISION,
    "productOptionName1" TEXT,
    "productOptionType1" TEXT,
    "productOptionDescription1" TEXT,
    "productOptionName2" TEXT,
    "productOptionType2" TEXT,
    "productOptionDescription2" TEXT,
    "productOptionName3" TEXT,
    "productOptionType3" TEXT,
    "productOptionDescription3" TEXT,
    "productOptionName4" TEXT,
    "productOptionType4" TEXT,
    "productOptionDescription4" TEXT,
    "productOptionName5" TEXT,
    "productOptionType5" TEXT,
    "productOptionDescription5" TEXT,
    "productOptionName6" TEXT,
    "productOptionType6" TEXT,
    "productOptionDescription6" TEXT,
    "additionalInfoTitle1" TEXT,
    "additionalInfoDescription1" TEXT,
    "additionalInfoTitle2" TEXT,
    "additionalInfoDescription2" TEXT,
    "additionalInfoTitle3" TEXT,
    "additionalInfoDescription3" TEXT,
    "additionalInfoTitle4" TEXT,
    "additionalInfoDescription4" TEXT,
    "additionalInfoTitle5" TEXT,
    "additionalInfoDescription5" TEXT,
    "additionalInfoTitle6" TEXT,
    "additionalInfoDescription6" TEXT,
    "customTextField1" TEXT,
    "customTextCharLimit1" INTEGER,
    "customTextMandatory1" BOOLEAN,
    "customTextField2" TEXT,
    "customTextCharLimit2" INTEGER,
    "customTextMandatory2" BOOLEAN,
    "brand" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);
